### ISSUE TITLE
Please could you kindly share a code that could make image centered

### ISSUE THREAD

**Issue by specialosis** [hmbashar/POST-URL-QR-CODE#1]
Firstly I wanted to Thank you for this beautiful plugin
Could you kindly share a code that could be used to make the QR image centred

**Comment by hmbashar** [comment]
> 
> 
> Firstly I wanted to Thank you for this beautiful plugin
> Could you kindly share a code that could be used to make the QR image centred

Add this code in your style.css file
```
.cb-post-url-qr-code {
    text-align: center;
}
```

**Comment by specialosis** [comment]
Thanks, you are the best.
